version: "3"

services:
  app:
    build:
      dockerfile: Dockerfile
      context: ./app/
    networks:
      - social-network-4
    ports:
      - 3000:3000
    environment:
      DB_USER: user
      DB_PASS: password
      DB_ADDR: db
      DB_NAME: social-network-4
      JWT_SECRET_KEY: SecretYouShouldHide
      PORT: 3000
    depends_on:
      - migration
      - db
  migration:
    image: migrate/migrate
    volumes:
      - ./db/migrations:/migrations
    command: -database 'mysql://user:password@tcp(db)/social-network-4' -path=/migrations/ up
    networks:
      - social-network-4
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'social-network-4'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      LANG: C.UTF-8
    volumes:
      - ./db/data:/var/lib/mysql
    networks:
      - social-network-4
    ports:
      - 3306:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

networks:
  social-network-4:
