apiVersion: apps/v1
kind: Deployment
metadata:
    name: otus-deployment
spec:
    replicas: 3
    selector:
       matchLabels:
          app: otus-app
    template:
       metadata:
          labels:
             app: otus-app
       spec:
          containers:
          - name: otus-app
            image: antropovivan/otus:microservices-docker
            ports:
              - name: health
                containerPort: 8000
