version: "3"

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'social-network'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      LANG: C.UTF-8
    volumes:
      - .mysql-data:/var/lib/mysql
      - ./people.csv:/people.csv
    ports:
      - 3306:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
