# DB_USER=user
# DB_PASS=password
# DB_ADDR=otus-db
# DB_NAME=users
# echo -n 'admin' | base64
apiVersion: v1
kind: Secret
metadata:
  name: otus-secrets
data:
  db_user: dXNlcg==
  db_password: cGFzc3dvcmQ=
  db_addr: bXlzcWwtbWluaWt1YmU=
  db_name: b3R1cy1kYg==
type: Opaque
